### PR TITLE
new msg to add vehicle wheel status info to vehicle status

### PR DESCRIPTION
**Pull request by ChrisFajardo-TRI**
velocity, height, pitch_angle, steer_angle

### CODE REVIEW

**Comment by ChrisFajardo-TRI** [comment]
@andrewbest-tri @anrp-tri

**Review by andrewbest-tri — APPROVED** [review]
LGTM

**Comment by andrewbest-tri** [comment]
btw, for the future should we consider exposing this for other vehicles?

**Comment by ChrisFajardo-TRI** [comment]
> btw, for the future should we consider exposing this for other vehicles?

@andrewbest-tri 
we should be able to use these CarlaEgoVehicle* messages for any vehicle. the ros_bridge would just need to instantiate an "EgoVehicle" for any vehicle we care about getting this info for.

also minor update since your approval fyi

**Review by andrewbest-tri — APPROVED** [review]
nit: newlines at end of files are making github complain

**Review by andrewbest-tri — CHANGES_REQUESTED** [review]
reviewing other PR. We need units on these annotated in the messages or described in the fields.


slip is angles? fraction? radians, degrees etc?

Either comment message or change field for `foo_deg` and `foo_rad` for example

**Comment by ChrisFajardo-TRI** [comment]
@andrewbest-tri decided to use comments instead of variable name so that I can put more thorough information

**Review by andrewbest-tri — APPROVED** [review]
LGTM

**Pull request merged**
